random_seed: 2025
num_classes: 101
learning_rate: 0.001
batch_size: 256
num_epochs: 100
validation_percent: 0.05

cuda_device: 0   # Use 'cpu' if not available

# Weight init scheme: xavier_uniform, kaiming_normal, kaiming_uniform 
weight_init:
  name: xavier_uniform

optimizer: 
  name: RMSprop
  alpha: 0.99
  momentum: 0.0
  weight_decay: 0.0
  eps: 1e-08
  

scheduler:
  # ReduceLROnPlateau, ExponentialLR, StepLR
  name: ReduceLROnPlateau
  factor: 0.1
  mode: max
  patience: 5
