random_seed: 2025
num_classes: 101
learning_rate: 0.001
batch_size: 256
num_epochs: 100
validation_percent: 0.05
cuda_device: 0   # Use 'cpu' if not available

# Weight Init: xavier_uniform, kaiming_normal, kaiming_uniform 
weight_init:
  name: xavier_uniform

# Optimizer: Adam, SGD, SGD with Momentum, RMSProp
optimizer: 
  name: Adam
  weight_decay: 2e-4
  alpha: 0.99

# ReduceLROnPlateau, ExponentialLR, StepLR
scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  mode: max
  patience: 5